function fail = addF(lat, lon,tx)
%ADDF Summary of this function goes here
%   Detailed explanation goes here
rx = rxsite(...
'Latitude',lat, ...
'Longitude', lon, ...
'Antenna',design(dipole,tx.TransmitterFrequency), ...
'ReceiverSensitivity',-90);
show(rx);
fail = 1;
end

